version: "3.8"

services:
  filebeat:
    image: docker.elastic.co/beats/filebeat:${STACK_VERSION}
    restart: unless-stopped
    user: "root"
    environment:
      - TZ=Asia/Bangkok
      - ELASTICSEARCH_HOSTS=${ES_HOST}
      - ELASTICSEARCH_USERNAME=${ES_USERNAME}
      - ELASTICSEARCH_PASSWORD=${ES_PASSWORD}
      - NGINX_LOGS=${NGINX_LOGS}
    labels:
      - co.elastic.logs/enabled=false
      - co.elastic.logs/module=nginx
    volumes:
      - type: bind
        source: /var/log/nginx/${NGINX_LOGS}
        target: /var/log/nginx
      - type: bind
        source: ${PWD}/filebeat.docker.yml
        target: /usr/share/filebeat/filebeat.yml
        read_only: true
