filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.inputs:
- type: log
  paths:
    - /var/log/nginx/*.json
  tags: ["nginx", "json"]
  json:
    keys_under_root: true
    add_error_key: true

processors:
- add_cloud_metadata: ~

output.logstash:
  hosts: ["logstash:5400"]